// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UTNGolCoinApi.Data;

#nullable disable

namespace UTNGolCoinApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260722222520_ActualizarCamposPartido")]
    partial class ActualizarCamposPartido
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UTNGolCoinApi.Models.Billetera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Billeteras");
                });

            modelBuilder.Entity("UTNGolCoinApi.Models.BonoDiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BilleteraId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaBono")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BilleteraId");

                    b.ToTable("BonosDiarios");
                });

            modelBuilder.Entity("UTNGolCoinApi.Models.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CuotaEmpate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CuotaLocal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CuotaVisitante")
                        .HasColumnType("numeric");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fase")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaPartido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GolesLocal")
                        .HasColumnType("integer");

                    b.Property<int?>("GolesVisitante")
                        .HasColumnType("integer");

                    b.Property<string>("Grupo")
                        .HasColumnType("text");

                    b.Property<string>("NombreSede")
                        .HasColumnType("text");

                    b.Property<int?>("NumeroPartidoFifa")
                        .HasColumnType("integer");

                    b.Property<int?>("SedeId")
                        .HasColumnType("integer");

                    b.Property<string>("SeleccionLocal")
                        .HasColumnType("text");

                    b.Property<int?>("SeleccionLocalId")
                        .HasColumnType("integer");

                    b.Property<string>("SeleccionVisitante")
                        .HasColumnType("text");

                    b.Property<int?>("SeleccionVisitanteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("UTNGolCoinApi.Models.Prediccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BilleteraId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cuota")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontoApostado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PartidoCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartidoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResultadoPronosticado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Predicciones");
                });

            modelBuilder.Entity("UTNGolCoinApi.Models.Transaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BilleteraId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaTransaccion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BilleteraId");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("UTNGolCoinApi.Models.BonoDiario", b =>
                {
                    b.HasOne("UTNGolCoinApi.Models.Billetera", "Billetera")
                        .WithMany()
                        .HasForeignKey("BilleteraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Billetera");
                });

            modelBuilder.Entity("UTNGolCoinApi.Models.Transaccion", b =>
                {
                    b.HasOne("UTNGolCoinApi.Models.Billetera", "Billetera")
                        .WithMany("Transacciones")
                        .HasForeignKey("BilleteraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Billetera");
                });

            modelBuilder.Entity("UTNGolCoinApi.Models.Billetera", b =>
                {
                    b.Navigation("Transacciones");
                });
#pragma warning restore 612, 618
        }
    }
}
